/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TendenciaRouteImport } from './routes/tendencia'
import { Route as LojasRouteImport } from './routes/lojas'
import { Route as ComparativosRouteImport } from './routes/comparativos'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as IndexRouteImport } from './routes/index'

const TendenciaRoute = TendenciaRouteImport.update({
  id: '/tendencia',
  path: '/tendencia',
  getParentRoute: () => rootRouteImport,
} as any)
const LojasRoute = LojasRouteImport.update({
  id: '/lojas',
  path: '/lojas',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparativosRoute = ComparativosRouteImport.update({
  id: '/comparativos',
  path: '/comparativos',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categorias': typeof CategoriasRoute
  '/comparativos': typeof ComparativosRoute
  '/lojas': typeof LojasRoute
  '/tendencia': typeof TendenciaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categorias': typeof CategoriasRoute
  '/comparativos': typeof ComparativosRoute
  '/lojas': typeof LojasRoute
  '/tendencia': typeof TendenciaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categorias': typeof CategoriasRoute
  '/comparativos': typeof ComparativosRoute
  '/lojas': typeof LojasRoute
  '/tendencia': typeof TendenciaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/categorias' | '/comparativos' | '/lojas' | '/tendencia'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/categorias' | '/comparativos' | '/lojas' | '/tendencia'
  id:
    | '__root__'
    | '/'
    | '/categorias'
    | '/comparativos'
    | '/lojas'
    | '/tendencia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriasRoute: typeof CategoriasRoute
  ComparativosRoute: typeof ComparativosRoute
  LojasRoute: typeof LojasRoute
  TendenciaRoute: typeof TendenciaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tendencia': {
      id: '/tendencia'
      path: '/tendencia'
      fullPath: '/tendencia'
      preLoaderRoute: typeof TendenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lojas': {
      id: '/lojas'
      path: '/lojas'
      fullPath: '/lojas'
      preLoaderRoute: typeof LojasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparativos': {
      id: '/comparativos'
      path: '/comparativos'
      fullPath: '/comparativos'
      preLoaderRoute: typeof ComparativosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriasRoute: CategoriasRoute,
  ComparativosRoute: ComparativosRoute,
  LojasRoute: LojasRoute,
  TendenciaRoute: TendenciaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
